version: '3'
services:
  # Сервисы приложения
  app1:
    container_name: app1
    environment:
      APP_PORT: 8081
    image: rksp-pr5-service:0.0.1
    depends_on:
      - postgres_pr5  # Зависит от базы данных
    ports:
      - "8081:8081"

  app2:
    container_name: app2
    environment:
      APP_PORT: 8082
    image: rksp-pr5-service:0.0.1
    depends_on:
      - postgres_pr5
    ports:
      - "8082:8082"

  app3:
    container_name: app3
    environment:
      APP_PORT: 8083
    image: rksp-pr5-service:0.0.1
    depends_on:
      - postgres_pr5
    ports:
      - "8083:8083"

  app4:
    container_name: app4
    environment:
      APP_PORT: 8084
    image: rksp-pr5-service:0.0.1
    depends_on:
      - postgres_pr5
    ports:
      - "8084:8084"

  # Контейнер для Nginx
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4

  # Контейнер для PostgreSQL
  postgres_pr5:
    image: postgres:latest
    container_name: postgres_pr5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
